[package]
name = "rust-tag-server"
version = "0.1.0"
authors = ["Cory Kolbeck <cory.kolbeck@urbanairship.com>"]

[dependencies]

http = "0.1.16"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0.89"
serde_derive = "1.0.89"
